image:https://img.shields.io/badge/Java-11%2B-ED8B00?style=for-the-badge&labelColor=ED8B00&logo=java&color=808080[Java]
image:https://img.shields.io/jitpack/v/github/Natureknight/SimpleLock?style=for-the-badge&labelColor=007ec5&color=808080&logo=Git&logoColor=white[JitPack]
image:https://img.shields.io/badge/Spring%20Boot-2.7.5-ED8B00?style=for-the-badge&labelColor=6db33f&color=808080&logo=Spring%20Boot&logoColor=white[Spring Boot]
image:https://img.shields.io/github/license/Natureknight/SimpleLock?style=for-the-badge&color=808080&logo=Open%20Source%20Initiative&logoColor=white[License]

== SimpleLock for Spring Boot (JDBC)

Distributed lock ensures your method cannot be run in parallel from multiple JVMs (cluster of servers, microservices, ...).
It uses a common store to keep track of used locks and your method needs to acquire one or more locks to run.

By default, locks follow methods lifecycle.They are obtained at the start of the method and released at the end of the method.
Manual controlling is supported and explained later in this document.

All locks acquired by `SimpleLock` implementations in this project will expire after 1 second.
These options are customizable per annotation.

=== Manually controlled locks

Sometimes you might want lock to be acquired when calling a specific method and get released only when it expires (throttling).
Use the `releaseAfter` attribute to control the duration of holding the lock (in milliseconds, default is 1s (1000 ms))

==== Example

Using Spring Aspect:

[source,java]
----
@Component
public class MyJdbcLockedService {
    /**
     * Execute with distributed JDBC lock, by holding the lock for 5 minutes
     */
    @SimpleJdbcLocked(releaseAfter = 5L, timeUnit = TimeUnit.MINUTES)
    public void doSomething() {
        // locked method body
    }

    /**
     * Execute with distributed JDBC lock, by releasing the lock immediately
     */
    @SimpleJdbcLocked
    public void doSomethingElse() {
        // locked method body
    }
}
----

or programatically:

[source,java]
----
@Component
@RequiredArgsConstructor
public class MyJdbcLockedService {
    private final LockRunnableExecutor lockRunnableExecutor;

    /**
     * Execute with distributed JDBC lock, by holding the lock for 5 minutes
     */
    public void doSomething() {
        lockRunnableExecutor.executeLocked(() -> {
            // locked method body wrapped in java.lang.Runnable
        }, 5L, TimeUnit.MINUTES);
    }

    /**
     * Execute with distributed JDBC lock, by releasing the lock immediately
     */
    public void doSomethingElse() {
        lockRunnableExecutor.executeLocked(() -> {
            // locked method body wrapped in java.lang.Runnable
        });
    }
}
----

=== Unsuccessful locks

If method cannot be locked, the execution will be skipped.

Method might not acquire the lock if:

. Another method acquired the lock
. Lock implementation threw an exception

== Enabling locking

Project provides the following out-of-the-box `SimpleLock` implementations:

* JDBC
- JdbcSimpleLock

|===
|Annotation

|`@SimpleJdbcLocked`
|===

[NOTE]
====
The database table `simple_lock` will be created automatically.
====

== Importing into your project

=== Maven

Add the jitpack repository into your `pom.xml`
[source,xml]
----
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
----

Add the project dependency into your `pom.xml`
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>com.github.natureknight.simplelock</groupId>
    <artifactId>simplelock-spring-starter</artifactId>
    <version>1.1.6</version>
  </dependency>
</dependencies>
----

=== Gradle

Add the jitpack repository into your `build.gradle`
[source,groovy]
----
repositories {
    maven {
        url = 'https://jitpack.io'
    }
}
----

Add the project dependency into your `build.gradle`
[source,groovy]
----
implementation('com.github.natureknight.simplelock:simplelock-spring-starter:1.1.6')
----

=== Compatibility

|===
|Version |Spring Boot version

|1.+
|2.5.+

|===

== Customization

If you want to use custom lock implementations, simply implement `com.stanislav.simplelock.api.SimpleLock` interface and register it in a configuration.
You can also create an alias for your lock, so you don't have to specify `@SimpleJdbcLocked` type field.

== Changelog

=== 1.1.6

- Version bump

=== 1.1.5

- Fixed transitive dependency for SLF4J

=== 1.1.4

- Fixed an issue with DuplicateKeyException swallow due to previous commit

=== 1.1.3

- Skip execution if lock could not be acquired

=== 1.1.2

- Allow clients to choose the `TimeUnit` when holding the lock

=== 1.1.1

- Swallow JDBC exception in case lock could not be acquired

=== 1.1.0

- Release version
