image:https://sonarcloud.io/api/project_badges/measure?project=Natureknight_SimpleLock&metric=alert_status[SonarCloud Status]
image:https://sonarcloud.io/api/project_badges/measure?project=Natureknight_SimpleLock&metric=coverage[SonarCloud Coverage]
image:https://sonarcloud.io/api/project_badges/measure?project=Natureknight_SimpleLock&metric=bugs[SonarCloud Bugs]
image:https://sonarcloud.io/api/project_badges/measure?project=Natureknight_SimpleLock&metric=vulnerabilities[SonarCloud Vulnerabilities]
image:https://img.shields.io/badge/Java-11%2B-ED8B00?style=for-the-badge&labelColor=ED8B00&logo=java&color=808080[Java]
image:https://img.shields.io/jitpack/v/github/Natureknight/SimpleLock?style=for-the-badge&labelColor=007ec5&color=808080&logo=Git&logoColor=white[JitPack]
image:https://img.shields.io/badge/Spring%20Boot-2.7.5-ED8B00?style=for-the-badge&labelColor=6db33f&color=808080&logo=Spring%20Boot&logoColor=white[Spring Boot]
image:https://img.shields.io/github/license/Natureknight/SimpleLock?style=for-the-badge&color=808080&logo=Open%20Source%20Initiative&logoColor=white[License]

== SimpleLock for Spring Boot: (JDBC)

Distributed lock ensures your method cannot be run in parallel from multiple JVMs (cluster of servers, microservices, ...).
It uses a common store to keep track of used locks and your method needs to acquire lock to run.

By default, locks follow methods lifecycle.They are obtained at the start of the method and released at the end of the method.
Manual controlling is supported and explained later in this document.

All locks acquired by `SimpleLock` implementations in this project will expire after 10 seconds by default.
These options are customizable.

=== Manually controlled locks:

Use the `releaseAfter` attribute to control the duration of holding the lock (default is 10 seconds)

==== Example

Using `@SimpleJdbcLocked` annotation:

[source,java]
----
@Component
public class MyJdbcLockedService {

    /**
     * Invoke with distributed JDBC lock, by holding the lock for 5 minutes
     */
    @SimpleJdbcLocked(releaseAfter = 5L, timeUnit = TimeUnit.MINUTES)
    public void doSomething() {
        // locked method body
    }

    /**
     * Invoke with distributed JDBC lock, by releasing the lock immediately
     */
    @SimpleJdbcLocked
    public void doSomethingElse() {
        // locked method body
    }
}
----

or programmatically, where you're allowed to propagate the lock token further into your service and release the lock whenever suitable for your use case:

[source,java]
----
@Component
@RequiredArgsConstructor
@Slf4j
public class MyJdbcLockedService {

    private final SimpleLock simpleLock;

    /**
     * Invoke with distributed JDBC lock, by holding the lock for 5 minutes
     */
    public void doSomething() {
        Optional<String> tokenOptional = simpleLock.acquire("my-unique-lock-key");
        // IMPORTANT: lock has been acquired successfully only if the token is present,
        // so make sure you have this check wrapping your service logic that needs to be locked
        if (tokenOptional.isEmpty()) {
            return;
        }

        log.info("Some action executed concurrently");

        // IMPORTANT: Don't forget to release your lock after execution, unless your requirement
        // is to have it locked forever for some reason
        simpleLock.release(tokenOptional.get(), 5L, TimeUnit.MINUTES);
    }

    /**
     * Invoke with distributed JDBC lock, by releasing the lock immediately.
     * By using acquireForCurrentMethod, you will be able to lock another action(s)
     * for the same business ID, as the actual lock key in this case
     * will be "doSomething-KEY" where KEY will be the actual business ID
     */
    public void doSomething(UUID id) {
        simpleLock.acquireForCurrentMethod(id.toString())
                // IMPORTANT: lock has been acquired successfully only if the token is present,
                // so make sure you have this check wrapping your service logic that needs to be locked
                .ifPresent(token -> {
                    log.info("Some action executed concurrently for id={}", id);

                    // IMPORTANT: Don't forget to release your lock after execution, unless
                    // your requirement is to have it locked forever for some reason
                    simpleLock.release(token);
                });
    }
}
----

=== Unsuccessful locks:

If method cannot be locked, the execution will be skipped.

Method might not acquire the lock if:

. Another method/thread/service node acquired the lock
. Lock implementation threw an exception

== Enabling locking

Project provides the following out-of-the-box `SimpleLock` implementations:

* JDBC (see `JdbcSimpleLock`)

== Supported databases:

List of supported databases:

* MySQL
* MariaDB
* PostgreSQL
* Oracle
* H2

=== Configuration properties: (JDBC)

|===
| Property | Description | Default

| `simplelock.jdbc.enabled` | Whether the JDBC lock is enabled (Default: `true`) | `true`
| `simplelock.jdbc.auto-generate-ddl` | Whether to automatically create the DB object(s) | `true`
| `simplelock.jdbc.cleanup-on-startup` | Whether to clean up DB if any existing locks are not released | false
|===

|===
|Annotation

|`@SimpleJdbcLocked`
|===

== Importing into your project:

=== Maven

Add the jitpack repository into your `pom.xml`:
[source,xml]

----
<repositories>
  <repository>
    <id>jitpack.io</id>
    <url>https://jitpack.io</url>
  </repository>
</repositories>
----

Add the project dependency into your `pom.xml`:
[source,xml]

----
<dependencies>
  <dependency>
    <groupId>com.github.natureknight.simplelock</groupId>
    <artifactId>simplelock-spring-starter</artifactId>
    <version>1.5.9</version>
  </dependency>
</dependencies>
----

=== Gradle

Add the jitpack repository into your `build.gradle`:
[source,groovy]

----
repositories {
    maven {
        url = 'https://jitpack.io'
    }
}
----

Add the project dependency into your `build.gradle`:
[source,groovy]

----
implementation('com.github.natureknight.simplelock:simplelock-spring-starter:1.5.9')
----

=== Compatibility:

|===
|Version |Spring Boot version

|1.+
|2.5.+

|===

== Customization:

If you want to use custom lock implementations, simply implement `com.simplelock.api.SimpleLock` interface and register it in a configuration.

== Changelog:

=== 1.5.9

- Fixed reported Sonar issues

=== 1.5.8

- Added SonarCloud analysis
- Remove vulnerable transitive dependency

=== 1.5.5 - 1.5.7

- Update tests

=== 1.5.4

- Added list of supported databases and tests

=== 1.5.3

- Increase test coverage

=== 1.5.2

- Added tests for `simplelock-spring-starter-jdbc` module

=== 1.5.1

- Renamed few leftovers for `simplelock-spring-starter-jdbc`

=== 1.5.0

- Renamed module `simplelock-jdbc` to `simplelock-spring-starter-jdbc`

=== 1.4.1

- Update project structure
- Update README

=== 1.4.0

- By default, hold the lock for 10 seconds
- Update dependency tree
- Update project structure

=== 1.3.1

- Fixed an issue with functionality for appending the invoking method prefix

=== 1.3.0

- Added functionality to lock for same lock key but different invocation points

=== 1.2.7

- Update configuration properties by removing `com.github` prefix

=== 1.2.2 - 1.2.6

- Improved logging

=== 1.2.1

- Fixed an issue with transitive dependency for SLF4J

=== 1.2.0

- Added configuration properties
- Update README

=== 1.1.7

- Release lock synchronously in case `releaseAfter` is set to 0
- Improved logging

=== 1.1.6

- Version bump

=== 1.1.5

- Fixed transitive dependency for SLF4J

=== 1.1.4

- Fixed an issue with DuplicateKeyException swallow due to previous commit

=== 1.1.3

- Skip execution if lock could not be acquired

=== 1.1.2

- Allow clients to choose the `TimeUnit` when holding the lock

=== 1.1.1

- Swallow JDBC exception in case lock could not be acquired

=== 1.1.0

- Release version
