name: Create Release

on:
  push:
    tags:
      - 'v[0-9]{1,10}+.[0-9]{1,10}+.[0-9]{1,10}+-beta[0-9]{1,10}'
      - 'v[0-9]{1,10}+.[0-9]{1,10}+.[0-9]{1,10}+-SNAPSHOT'
      - 'v[0-9]{1,10}+.[0-9]{1,10}+.[0-9]{1,10}+-rc[0-9]{1,10}'

jobs:
  build:
    name: Create Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Pre-Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: true
